// src/pages/CommunityPost.jsx
import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import apiClient from '../api/axios';
import { FaMapMarkerAlt, FaUser, FaCalendarAlt, FaArrowLeft } from 'react-icons/fa';
import { format } from 'date-fns';

const CommunityPost = () => {
  const { slug } = useParams();
  const [post, setPost] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchPost = async () => {
      try {
        const { data } = await apiClient.get(`/community/post/${slug}`);
        setPost(data);
      } catch (err) {
        console.error("Failed to fetch post:", err);
        setError('Post not found or has been removed.');
      } finally {
        setLoading(false);
      }
    };

    fetchPost();
  }, [slug]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-950">
        <div className="w-12 h-12 border-4 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  if (!post) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 dark:bg-gray-950">
        <h1 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">Post Not Found</h1>
        <Link to="/" className="text-blue-600 hover:underline">Go Home</Link>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 py-10 px-4">
      
      {/* --- SEO METADATA --- */}
      <Helmet>
        <title>{post.metaTitle || post.title} | HouseHunt Kenya Community</title>
        <meta name="description" content={post.metaDescription} />
        <meta property="og:title" content={post.title} />
        <meta property="og:description" content={post.metaDescription} />
        <meta property="og:type" content="article" />
        <link rel="canonical" href={`https://www.househuntkenya.co.ke/community/${post.slug}`} />
      </Helmet>

      <article className="max-w-3xl mx-auto bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden border border-gray-100 dark:border-gray-700">
        
        {/* Header */}
        <div className="p-8 border-b border-gray-100 dark:border-gray-700">
          <Link 
            to={`/search/rent/${post.location}`} 
            className="inline-flex items-center text-sm text-purple-600 dark:text-purple-400 mb-4 hover:underline"
          >
            <FaArrowLeft className="mr-2" /> Browse properties in {post.location}
          </Link>
          
          <h1 className="text-3xl md:text-4xl font-extrabold text-gray-900 dark:text-white mb-6 leading-tight">
            {post.title}
          </h1>

          <div className="flex flex-wrap items-center text-sm text-gray-500 dark:text-gray-400 gap-4 md:gap-6">
            <span className="flex items-center">
              <FaUser className="mr-2 text-gray-400" /> {post.authorName}
            </span>
            <span className="flex items-center">
              <FaMapMarkerAlt className="mr-2 text-gray-400" /> {post.location}
            </span>
            <span className="flex items-center">
              <FaCalendarAlt className="mr-2 text-gray-400" /> {format(new Date(post.createdAt), 'MMMM d, yyyy')}
            </span>
          </div>
        </div>

        {/* Content Body */}
        <div className="p-8 md:p-10">
          {/* ✅ CRITICAL: This renders the "processedContent" 
              which contains the Internal Links generated by your AutoLinker 
          */}
          <div 
            className="prose prose-lg dark:prose-invert max-w-none text-gray-700 dark:text-gray-300 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: post.processedContent }}
          />
        </div>

        {/* Footer CTA */}
        <div className="bg-gray-50 dark:bg-gray-900/50 p-8 border-t border-gray-100 dark:border-gray-700 text-center">
          <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-2">
            Inspired? Share your story.
          </h3>
          <p className="text-gray-600 dark:text-gray-400 mb-4 text-sm">
            Help others discover the best places to live in Nairobi.
          </p>
          <Link 
            to="/share-insight" 
            className="inline-block bg-purple-600 hover:bg-purple-700 text-white font-bold py-3 px-6 rounded-lg transition shadow-md"
          >
            Write a Neighborhood Review
          </Link>
        </div>

      </article>
    </div>
  );
};

export default CommunityPost;